config/routes.rb
SonkwoCommunity::Application.routes.draw do
  begin
    devise_for :accounts, :controllers => { :sessions => 'account_sessions', :registrations => 'account_registrations' }
    devise_scope :accounts do
      get '/accounts/sign_out', to: 'account_sessions#destroy' # used for other platforms(store, forum)
    end
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end
  root :to => "home_pages#index"
  resources :home_pages, only: [:index]
  resources :groups do
    member do
      put 'add_user'
      delete 'remove_user'
      post 'add_tags'
      get 'posts'
      get 'members'
    end
    resources :posts, only: [:create]
  end

  resources :posts do
    resources :comments
    member do
      put 'like'
      delete 'unlike'
      post 'recommend'
    end
    resources :post_images, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    collection do
      put 'follow'
      delete 'unfollow'
      get 'check_name'
    end
    member do
      get 'groups'
      get 'posts'
      get 'people'
      get 'games'
      get 'games/:game_id', to: 'users#game'
      get 'games/:game_id/game_achievements', to: 'users#game_achievements'
    end
    resources :albums, only: [:index, :create, :show, :new] do
      resources :photos, only: [:index, :create]
    end
  end
  post 'photos/screenshot', to: 'photos#screenshot'

  resources :home, only: [:index] do
    collection do
      get 'index'
      get 'groups'
      get 'people'
      get 'posts'
      get 'notification'
      get 'recommended'
      put 'tags/:tag_id', to: 'home#add_tag'
      delete 'tags/:tag_id', to: 'home#remove_tag'
    end
  end

  resources :conversations, only: [:index, :show, :destroy]
  resources :private_messages, only: [:create, :destroy]
  resources :setting, only: [:index] do
    collection do
      get 'security'
      get 'password'
      put 'password', to: 'setting#update_password'
      post 'bind'
      get 'bind_complete'
    end
  end

  resources :cloud_storages, only: [:new, :create] do
    collection do
      get 'template'
    end
  end

  resources :games, only: [] do
    resources :game_achievements, only: [:index, :show]
    member do
      get :ranklist
    end
  end

  resources :informations, only: [:index] do
    collection do
      get :groups
      get :friends
      get :clients
      get :tags
      post :confirm_step
    end
  end

  resources :tipoffs, only: [:create]

  scope "(:locale)", locale: /zh|en/ do
    get '/admin', to: 'admin#index'
    namespace :admin do
      resources :games, only: [:index, :destroy] do
        member do
          get :pre_release_list
          get :submit_release
          get :new_pre_release
          get :audit_release
          get :game_serial_numbers
          get :delete_selection
          get :game_serial_type
          post :pre_release_list
          post :submit_release
          post :new_pre_release
          post :cancel_pre_release
          post :audit_release
          put :import_serials
          put :game_serial_type
        end
      end
      resources :auth_items
      resources :accounts, only: [:index, :edit]
      resources :serial_types
      resources :download_servers
      resources :clients
      resources :recommendations
      resources :all_games do
        resources :achievements
      end
    end
    resources :auth_items
    resources :accounts, only: [:index, :edit]
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # old routes (need to be cleaned in future)
  namespace :api do
    post 'client/post_err_msg', to: 'client#post_err_msg'
    get 'client/get_latest_client_version', to: 'client#get_latest_client_version'
    post 'user/post_action', to: 'user#post_action'
    post 'user/update_env', to: 'user#update_env'
    get 'user/get_play_time', to: 'user#get_play_time'
    get 'launch/get_launcher', to: 'launch#get_launcher'
    get 'game/list_my_games', to: 'game#list_my_games'
    get 'game/list_my_game_ids', to: 'game#list_my_game_ids'
    get 'game/get_game_info', to: 'game#get_game_info'
    get 'game/get_game_dlcs', to: 'game#get_game_dlcs'
    get 'game/request_game_shell', to: 'game#request_game_shell'
    get 'game/request_game_ini', to: 'game#request_game_ini'
    get 'game/get_game_seed', to: 'game#get_game_seed'
    get 'game/get_game_serial_number', to: 'game#get_game_serial_number'
    post 'game/register_serial_number', to: 'game#register_serial_number'
    get 'game/get_game_news', to: 'game#get_game_news'

  end
  # match ':controller(/:action(/:id))(.:format)'
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :games, only: [:index, :destroy] do
      member do
        get :pre_release_list
        get :submit_release
        get :new_pre_release
        get :audit_release
        get :game_serial_numbers
        get :delete_selection
        get :game_serial_type
        post :pre_release_list
        post :submit_release
        post :new_pre_release
        post :cancel_pre_release
        post :audit_release
        put :import_serials
        put :game_serial_type
      end
      resources:serial_numbers, only: [:index, :create], shallow: true do
        collection do
          get :delete_selection
          delete :delete_serials
          post :import
        end
      end
    end
    resources :auth_items
    resources :accounts
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # search api
  get 'search', to: 'search#index'
  get 'search/users', to: 'search#users'
  get 'search/posts', to: 'search#posts'
  get 'search/groups', to: 'search#groups'
end

app/controllers/admin/achievements_controller.rb
class Admin::AchievementsController < AdminController
  # GET /admin/achievements
  # GET /admin/achievements.json
  def index
    @admin_achievements = GameAchievement.where('game_id=?', params[:all_game_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @admin_achievements }
    end
  end

  # GET /admin/achievements/1
  # GET /admin/achievements/1.json
  def show
    @admin_achievement = GameAchievement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_achievement }
    end
  end

  # GET /admin/achievements/new
  # GET /admin/achievements/new.json
  def new
    @admin_achievement = AllGame.find(params[:all_game_id]).game_achievements.build
    @admin_achievement.subable = @admin_achievement.get_subable

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_achievement }
    end
  end

  # GET /admin/achievements/1/edit
  def edit
    @admin_achievement = GameAchievement.find(params[:id])
  end

  # POST /admin/achievements
  # POST /admin/achievements.json
  def create
    game = AllGame.find(params[:all_game_id])
    game_achievement = game.game_achievements.build(params[:game_achievement])
    game_achievement.subable.steam_game_id = game.subable_id
    respond_to do |format|
      if game_achievement.save
        format.html { redirect_to admin_all_game_achievements_path, notice: 'Achievement was successfully created.' }
      else
        format.html { redirect_to new_admin_all_game_achievement_path}
      end
    end
  end

  # PUT /admin/achievements/1
  # PUT /admin/achievements/1.json
  def update
    @admin_achievement = GameAchievement.find(params[:id])

    respond_to do |format|
      if @admin_achievement.update_attributes(params[:game_achievement])
        format.html { redirect_to admin_all_game_achievements_path, notice: 'Achievement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/achievements/1
  # DELETE /admin/achievements/1.json
  def destroy
    raise "Can't delete achievments, please using edit instead"
    @admin_achievement = GameAchievement.find(params[:id])
    @admin_achievement.subable.delete
    @admin_achievement.delete

    respond_to do |format|
      format.html { redirect_to admin_all_game_achievements_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/achievements_helper.rb
module Admin::AchievementsHelper
end

app/views/admin/achievements/_form.html.slim
= form_for [:admin_all, @admin_achievement], class: 'form-horizontal' do |f|
  - if @admin_achievement.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_achievement.errors.count, "error")} prohibited this admin_achievement from being saved:"
      ul
        - @admin_achievement.errors.full_messages.each do |message|
          li = message
  .form-group
    label for='name' =GameAchievement.human_attribute_name(:name)
    =f.text_field(:name, class: 'form-control')
  .form-group
    label for='description' =GameAchievement.human_attribute_name(:description)
    =f.text_area(:description, class: 'form-control')
  .form-group
    = f.fields_for :subable do |detail|
      .form-group
        label for='api_name' =SteamGameAchievement.human_attribute_name(:api_name)
        = detail.text_field(:api_name, class: 'form-control')
        = f.hidden_field :subable_type, value: @admin_achievement.subable_type
      .form-group
        label for='percent' =SteamGameAchievement.human_attribute_name(:percent)
        =detail.text_field(:percent, class: 'form-control')
  .form-group
    /todo : replace the hidden default value to file chose button
    label =GameAchievement.human_attribute_name(:lock_url)
    =f.hidden_field(:lock_url, value: Settings.images.game.default)
  .form-group
    label =GameAchievement.human_attribute_name(:unlock_url)
    =f.hidden_field(:unlock_url, value: Settings.images.game.default)
  .actions = f.submit 'Save'

app/views/admin/achievements/edit.html.slim
=render 'admin/games/nav'
-content_for :content do
  == render 'form'
  = link_to 'Back', admin_all_game_achievements_path

app/views/admin/achievements/index.html.slim
=render 'admin/games/nav'
-content_for :content do
  .row
    ul#my_tab.nav.nav-tabs
      li id="steam_games"
        =link_to('Steam', '#steam')
    .tab-content
      #steam.tab-pane.active
        table.table.table-striped.table-bordered.table-condensed
          tr
            th=GameAchievement.human_attribute_name(:name)
            th=GameAchievement.human_attribute_name(:lock_url)
            th=GameAchievement.human_attribute_name(:unlock_url)
          - @admin_achievements.each do |admin_achievement|
            tr
              td = admin_achievement.name
              td = image_tag(admin_achievement.lock_url)
              td = image_tag(admin_achievement.unlock_url)
              td = link_to 'Edit', edit_admin_all_game_achievement_path(admin_achievement.id, all_game_id: params[:all_game_id])
              td = link_to 'Destroy', admin_all_game_achievement_path(params[:all_game_id], admin_achievement.id), data: {:confirm => 'Are you sure?'}, :method => :delete
        = t('admin.msg.no_data') if @admin_achievements.empty?
        div
          = link_to 'New Achievement', new_admin_all_game_achievement_path

app/views/admin/achievements/new.html.slim
=render 'admin/games/nav'
-content_for :content do
  == render 'form'

app/views/admin/achievements/show.html.slim
p#notice = notice


= link_to 'Edit', edit_admin_achievement_path(@admin_achievement)
'|
= link_to 'Back', admin_achievements_path