config/routes.rb
SonkwoCommunity::Application.routes.draw do
  begin
    devise_for :accounts, :controllers => { :sessions => 'account_sessions', :registrations => 'account_registrations' }
    devise_scope :accounts do
      get '/accounts/sign_out', to: 'account_sessions#destroy' # used for other platforms(store, forum)
    end
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end
  root :to => "home_pages#index"
  resources :home_pages, only: [:index]
  resources :groups do
    member do
      put 'add_user'
      delete 'remove_user'
      post 'add_tags'
      get 'posts'
      get 'members'
    end
    resources :posts, only: [:create]
  end

  resources :posts do
    resources :comments
    member do
      put 'like'
      delete 'unlike'
      post 'recommend'
    end
    resources :post_images, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    collection do
      put 'follow'
      delete 'unfollow'
      get 'check_name'
    end
    member do
      get 'groups'
      get 'posts'
      get 'people'
      get 'games'
      get 'games/:game_id', to: 'users#game'
      get 'games/:game_id/game_achievements', to: 'users#game_achievements'
    end
    resources :albums, only: [:index, :create, :show, :new] do
      resources :photos, only: [:index, :create]
    end
  end
  post 'photos/screenshot', to: 'photos#screenshot'

  resources :home, only: [:index] do
    collection do
      get 'index'
      get 'groups'
      get 'people'
      get 'posts'
      get 'notification'
      get 'recommended'
      put 'tags/:tag_id', to: 'home#add_tag'
      delete 'tags/:tag_id', to: 'home#remove_tag'
    end
  end

  resources :conversations, only: [:index, :show, :destroy]
  resources :private_messages, only: [:create, :destroy]
  resources :setting, only: [:index] do
    collection do
      get 'security'
      get 'password'
      put 'password', to: 'setting#update_password'
      post 'bind'
      get 'bind_complete'
    end
  end

  resources :cloud_storages, only: [:new, :create] do
    collection do
      get 'template'
    end
  end

  resources :games, only: [] do
    resources :game_achievements, only: [:index, :show]
    member do
      get :ranklist
    end
  end

  resources :informations, only: [:index] do
    collection do
      get :groups
      get :friends
      get :clients
      get :tags
      post :confirm_step
    end
  end

  resources :tipoffs, only: [:create]

  scope "(:locale)", locale: /zh|en/ do
    get '/admin', to: 'admin#index'
    namespace :admin do
      resources :games, only: [:index, :destroy] do
        member do
          get :pre_release_list
          get :submit_release
          get :new_pre_release
          get :audit_release
          get :game_serial_numbers
          get :delete_selection
          get :game_serial_type
          post :pre_release_list
          post :submit_release
          post :new_pre_release
          post :cancel_pre_release
          post :audit_release
          put :import_serials
          put :game_serial_type
        end
      end
      resources :auth_items
      resources :accounts, only: [:index, :edit]
      resources :serial_types
      resources :download_servers
      resources :clients
      resources :recommendations
      resources :all_games do
        resources :achievements
      end
    end
    resources :auth_items
    resources :accounts, only: [:index, :edit]
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # old routes (need to be cleaned in future)
  namespace :api do
    post 'client/post_err_msg', to: 'client#post_err_msg'
    get 'client/get_latest_client_version', to: 'client#get_latest_client_version'
    post 'user/post_action', to: 'user#post_action'
    post 'user/update_env', to: 'user#update_env'
    get 'user/get_play_time', to: 'user#get_play_time'
    get 'launch/get_launcher', to: 'launch#get_launcher'
    get 'game/list_my_games', to: 'game#list_my_games'
    get 'game/list_my_game_ids', to: 'game#list_my_game_ids'
    get 'game/get_game_info', to: 'game#get_game_info'
    get 'game/get_game_dlcs', to: 'game#get_game_dlcs'
    get 'game/request_game_shell', to: 'game#request_game_shell'
    get 'game/request_game_ini', to: 'game#request_game_ini'
    get 'game/get_game_seed', to: 'game#get_game_seed'
    get 'game/get_game_serial_number', to: 'game#get_game_serial_number'
    post 'game/register_serial_number', to: 'game#register_serial_number'
    get 'game/get_game_news', to: 'game#get_game_news'

  end
  # match ':controller(/:action(/:id))(.:format)'
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :games, only: [:index, :destroy] do
      member do
        get :pre_release_list
        get :submit_release
        get :new_pre_release
        get :audit_release
        get :game_serial_numbers
        get :delete_selection
        get :game_serial_type
        post :pre_release_list
        post :submit_release
        post :new_pre_release
        post :cancel_pre_release
        post :audit_release
        put :import_serials
        put :game_serial_type
      end
      resources:serial_numbers, only: [:index, :create], shallow: true do
        collection do
          get :delete_selection
          delete :delete_serials
          post :import
        end
      end
    end
    resources :auth_items
    resources :accounts
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # search api
  get 'search', to: 'search#index'
  get 'search/users', to: 'search#users'
  get 'search/posts', to: 'search#posts'
  get 'search/groups', to: 'search#groups'
end

app/models/game.rb
class Game < ActiveRecord::Base
  STATUS_NORMAL = 1
  TYPE_GAME = 1
  belongs_to :parent, class_name: "Game", foreign_key: "parent_id"
  has_many :game_files
  has_many :game_serial_numbers
  has_many :recommendations, foreign_key: 'link'
  scope :no_releases, -> {select('id, title, alias_name').includes(:game_files).where(:game_files =>{:game_id => nil})}

  def serial_type_arr=(arr)
    # puts "publisher_arr=#{arr}"

    @serial_type_arr = arr
    #@serial_type_arr = []

    #arr.each do |be_bit|
    #  if be_bit[1] == "1"
    #    @serial_type_arr.push(be_bit[0].to_i)
    #  end
    #end
  end

  def serial_type_arr
    if @serial_type_arr == nil
      @serial_type_arr = []
    end

    @serial_type_arr
  end
end

app/controllers/admin/games_controller.rb
# -*- coding: utf-8 -*-
require 'uuidtools'
#require 'common/workflow_service'
class Admin::GamesController < AdminController
  def index
    @q = GameFile.search(params[:q])
    @games = @q.result.page(params[:page]).per(10)
    @not_released_games = Game.no_releases.page(params[:un_release_page]).per(10)

    respond_to do |format|
      format.html # index.html.slim
      format.xml  { render :xml => @admin_games }
    end
  end

  # DELETE /admin_games/1
  # DELETE /admin_games/1.xml
  def destroy
    @game = Game.find(params[:id])
    form_data = params[:admin_game_serial_number_delete_form]
    #start_time = Time.parse(form_data[:start_time])
    #end_time = Time.parse(form_data[:end_time])

    @delete_form = Admin::GameSerialNumberDeleteForm.new(form_data)

    game_id = params[:admin_game_serial_number_delete_form][:game_id]
    @game = Game.find(game_id)

    if @delete_form.valid?
      ActiveRecord::Base.transaction do
        @all_count = GameSerialNumber.where("game_id=? AND batch_number=? AND serial_type=? AND created_at>=? AND created_at<=?", @delete_form.game_id, @delete_form.batch_number, @delete_form.serial_type, @delete_form.start_time, @delete_form.end_time).count
        @used_count = GameSerialNumber.where("status<>? AND game_id=? AND batch_number=? AND serial_type=? AND created_at>=? AND created_at<=?", GameSerialNumber::STATUS_FRESH, @delete_form.game_id, @delete_form.batch_number, @delete_form.serial_type, @delete_form.start_time, @delete_form.end_time).count
        GameSerialNumber.destroy_all(["status=? AND game_id=? AND batch_number=? AND serial_type=? AND created_at>=? AND created_at<=?", GameSerialNumber::STATUS_FRESH, @delete_form.game_id, @delete_form.batch_number, @delete_form.serial_type, @delete_form.start_time, @delete_form.end_time])
      end
    else
      flash[:error] = t('admin.serial.delete_failed')
    end
    flash[:notice] = t('admin.msg.success')
    redirect_to game_serial_numbers_admin_game_path(@game)
  end


  def search
    @admin_games = Game.where("title like ?", "%#{params[:query]}%").page(params[:page]).per(10)
    render :index
  end

  def pre_release_list
    id = params[:id]
    @game = Game.find(id)
    @prev_game_files = GameFile.where('game_id=?', id).order('created_at DESC').limit(10)

    respond_to do |format|
      format.html
      format.xml  { render :xml => @prev_game_files }
    end
  end

  def new_pre_release
    game_id = params[:id]

    game_shell = params[:game_shell]
    game_ini = params[:game_ini]
    file_dir = params[:file_dir]
    crypt_type = params[:crypt_type]
    exe_path_name = params[:exe_path_name]

    @game = Game.find(game_id)
    @have_released = GameFile.select('id').where('game_id=? AND (status =? OR status = ?)', game_id, GameFile::STATUS_NEW, GameFile::STATUS_TO_VERIFY).first
    @prev_game_files = GameFile.where('game_id=?', game_id).order('created_at DESC')
    @game_file = @game.game_files.new

    @crypt_types = []
    i=0
    t('admin.game.crypt_types').each do |sta|
      @crypt_types << [sta, i]
      i += 1
    end

    begin
      socket = TCPSocket.new(Settings.sys_params.file_server_host, Settings.sys_params.file_server_port)
      socket.puts("LIST_DIR##{@game.alias_name}")
      dirs_json = socket.gets
      socket.close     
    rescue Exception => e
      raise e.inspect + t('admin.errors.could_not_conect_to_release_server')
    end


    @release_dirs = ActiveSupport::JSON.decode(dirs_json)

    prev_valideted_game_files = GameFile.where('game_id=? AND status=?', game_id, GameFile::STATUS_VALIDATED).order('created_at DESC')

    @release_dirs.delete("initial") unless prev_valideted_game_files.empty?

    if request.post?
      ActiveRecord::Base.transaction do
        if !game_ini && !game_shell && !crypt_type
          @game_file.errors[:base] << t('admin.err.release_content_missing')
          return
        end

        @game_file.game_id = game_id
        latest_game_file = GameFile.where('game_id=?', game_id).order('created_at DESC').lock('LOCK IN SHARE MODE').first

        if latest_game_file
          prev_ini_ver = latest_game_file.ini_ver
          prev_shell_ver = latest_game_file.shell_ver
          prev_patch_ver = latest_game_file.patch_ver
        else
          prev_ini_ver = 0
          prev_shell_ver = 0
          prev_patch_ver = -1
        end

        if game_shell
          @game_file.game_shell = game_shell.read
          @game_file.shell_digest = Digest::SHA1.hexdigest(@game_file.game_shell)
          @game_file.shell_ver = prev_shell_ver + 1
        elsif latest_game_file
          @game_file.game_shell = latest_game_file.game_shell
          @game_file.shell_digest = latest_game_file.shell_digest
          @game_file.shell_ver = prev_shell_ver
        else
          @game_file.errors[:base] << t('admin.err.game_shell_not_exist')
        end

        if game_ini
          @game_file.game_ini = game_ini.read
          @game_file.ini_digest = Digest::SHA1.hexdigest(@game_file.game_ini)
          @game_file.ini_ver = prev_ini_ver + 1
        elsif latest_game_file
          @game_file.game_ini = latest_game_file.game_ini
          @game_file.ini_digest = latest_game_file.ini_digest
          @game_file.ini_ver = prev_ini_ver
        else
          @game_file.errors[:base] << t('admin.err.game_ini_not_exist')
        end


        if file_dir
          if file_dir.strip.length == 0
            @game_file.errors[:base] << t('admin.err.game_dir_not_specified')
          end

          @game_file.file_dir = file_dir
          @game_file.crypt_type = crypt_type

          if crypt_type.to_i != Launcher::CRYPT_TYPE_EXTERNAL
            if exe_path_name == nil || exe_path_name.strip.length == 0
              @game_file.errors[:base] << t('admin.err.game_exe_not_specified')
            else
              @game_file.exe_path_name = exe_path_name
            end
          else
            @game_file.exe_path_name = ""
          end

          @game_file.patch_ver = prev_patch_ver + 1
          @game_file.status = GameFile::STATUS_NEW
        elsif latest_game_file
          @game_file.file_dir = latest_game_file.file_dir
          @game_file.crypt_type = latest_game_file.crypt_type
          @game_file.exe_path_name = latest_game_file.exe_path_name

          @game_file.game_key = latest_game_file.game_key
          @game_file.game_key_iv = latest_game_file.game_key_iv
          @game_file.key_digest = latest_game_file.key_digest

          @game_file.launcher_ver = latest_game_file.launcher_ver
          @game_file.patch_ver = prev_patch_ver
          @game_file.seed_content = latest_game_file.seed_content
          @game_file.seed_digest = latest_game_file.seed_digest
          @game_file.file_size = latest_game_file.file_size
          @game_file.status = GameFile::STATUS_TO_VERIFY
        else
          @game_file.errors[:base]  << t('admin.err.game_dir_not_specified')
        end


        if @game_file.errors.size == 0
          @game_file.save!
          Admin::PreReleaseWorker.perform_async(@game_file.id) if file_dir
          redirect_to pre_release_list_admin_game_path(game_id), notice: t('admin.msg.success')
        end
      end
    end
  end

  def cancel_pre_release
    if request.post?
      game_id = params[:id]
      game_file_id = params[:game_file_id]

      ActiveRecord::Base.transaction do
        game_file = GameFile.find(game_file_id, lock: true)

        if !game_file
          err = t('admin.err.game_file_not_exist')
        else
          game = Game.find(game_id)

          flow_status = {}
          flow_status[GameFile::STATUS_NEW] = "STATUS_NEW"
          flow_status[GameFile::STATUS_TO_VERIFY] = "STATUS_TO_VERIFY"

          if game_file.status != GameFile::STATUS_NEW && game_file.status != GameFile::STATUS_TO_VERIFY

          else
            #new_status, rcpt, cc, msg_title, msg_body = WorkflowService.process("release_game", flow_status[game_file.status], "on_cancel", {:game_name => game.title, :game_file_id => game_file.id})
            game_file.status = GameFile::STATUS_CANCELED   #eval("GameFile::#{new_status}")
            game_file.save!

            #flow_err = WorkflowService.send_notification(rcpt, cc, msg_title, msg_body)
            # raise ActiveRecord::Rollback if flow_err
          end

          if err
            flash[:error] = err
          else
            flash[:notice] = "Successfully canceled."
          end

          redirect_to pre_release_list_admin_game_path(game_file.game_id)
          return
        end
      end
    end
  end

  def get_exe_files
    socket = TCPSocket.new(Settings.sys_params.file_server_host, Settings.sys_params.file_server_port)
    socket.puts("LIST_EXE##{params[:game_name]}##{params[:file_dir]}")

    exes_json = socket.gets
    socket.close

    render :json => exes_json
  end

  def release_search
    @release_to_audit_cnt = GameFile.status_to_verify.count
    @release_to_audit_cnts = GameFile.select('status, COUNT(id) AS release_count').group('status')
    @select_options = []
    i=0

    t('admin.game.audit_status').each do |sta|
      @select_options << [sta, i]
      i += 1
    end

    @search_reault = nil


    conditions = ['title LIKE ?', params[:game_name]]

    if params[:audit_status] != "-1"
      conditions[0] += ' AND game_files.status=?'
      conditions << params[:audit_status]
    end

    @search_reault = Game.joins(:game_files).where(conditions).paginate(
        :select=>"game_files.id, game_id, title, created_at, crypt_type, file_dir, exe_path_name, process_start_time, process_finish_time, process_result, ini_ver, shell_ver, patch_ver, game_files.status, created_at",
        :order=>"created_at DESC",
        :per_page => 10,
        :page => params[:page]
    )

    # render :layout => false
  end


  def audit_release
    err = nil
    game_id = params[:id]
    @game = Game.select('id, title').where('id = ?', game_id).first
    game_file_id = params[:game_file_id]

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def ranklist
    @game = AllGame.find(params[:id])
    @ranklists = @game.ranklists.order("reputation DESC").fill_account
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/helpers/admin/games_helper.rb
# -*- encoding : utf-8 -*-
# require 'RMagick'

module Admin::GamesHelper
  def audited?(game_id,ids)
    for id in ids
      if  id == game_id
        return false
      end
    end
  end

  def resize_image?(src_filename, dest_filename, max_x=nil, max_y=nil)
    begin
      return false if (max_x == nil && max_y == nil)

      src_img = Magick::Image.read(src_filename).first

      x = src_img.columns
      y = src_img.rows
      ratio = (1.0*x)/y

      if max_y
        new_y = max_y
        new_x = ratio * new_y
      else
        new_x = max_x
        new_y = max_x / ratio
      end

      if new_x > max_x
        new_x = max_x
        new_y = new_x / ratio
      end

      src_img.resize!(x, new_y)
      src_img.resize!(new_x, new_y)

      src_img.write(dest_filename){self.quality = 80}
      true
    rescue
      false
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_nav.html.slim
-content_for :sidebar do
  - if check_access?({:auth_item => 'oper_game_files'})
    = link_to Game.model_name.human, admin_games_path, class: current_li?(%w(admin/games), params[:controller])
  - if check_access?({:auth_item => 'oper_serials'})
    = link_to GameSerialNumber.human_attribute_name(:serial_type), admin_serial_types_path, class: current_li?(%w(admin/serial_types), params[:controller])
  - if check_access?({:auth_item => 'oper_recommendations'})
    = link_to Recommendation.model_name.human, admin_recommendations_path, class: current_li?(%w(admin/recommendations), params[:controller])
  - if check_access?({:auth_item => 'oper_community_games'})
    = link_to AllGame.model_name.human, admin_all_games_path, class: current_li?(%w(admin/all_games admin/achievements), params[:controller])

app/views/admin/games/_released.html.slim
- if @games.empty?
  = t 'admin.msg.no_game'
- else
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th = Game.human_attribute_name(:title)
        th = GameFile.human_attribute_name(:status)
        th.text-center colspan=3  =t 'admin.game.release_process'
        th = GameSerialNumber.model_name.human
    tbody
      - @games.each do |g|
        tr class=tr_with_status(g.status)
          td title=g.game.alias_name =g.game.title
          td.danger =t('admin.game.release_status')[g.status]
          td
            -unless g.status == GameFile::STATUS_TO_VERIFY || g.status == GameFile::STATUS_NEW
              =link_to t('admin.titles.pre_release') + ' ', pre_release_list_admin_game_path(g.game_id)
              i.icon-arrow-right
          td
            - if g.status == GameFile::STATUS_TO_VERIFY || g.status == GameFile::STATUS_VALIDATED
              =link_to t('admin.titles.submit_release') + ' ', submit_release_admin_game_path(g.game_id)
              i.icon-arrow-right
          td
            - case g.status
            -when GameFile::STATUS_TO_VERIFY
              =link_to t('admin.game.release_pass'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_VALIDATED)
              |
              =link_to t('admin.game.release_not_pass'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_REJECTED)
            -when GameFile::STATUS_VALIDATED
              =link_to t('admin.game.rollback'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_ROLLBACKED)
            - else
              'ddd'
          td
            =link_to t('admin.game.serial_number'), game_serial_numbers_admin_game_path(g.game_id)

app/views/admin/games/_search.html.slim
- if @games.empty?
  = t 'admin.msg.no_game'
- else
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th = Game.human_attribute_name(:title)
        th = GameFile.human_attribute_name(:status)
        th.text-center colspan=3  =t 'admin.game.release_process'
        th = GameSerialNumber.model_name.human
    tbody
      - @games.each do |g|
        tr class=tr_with_status(g.status)
          td title=g.game.alias_name =g.game.title
          td.danger =t('admin.game.release_status')[g.status]
          td
            -unless g.status == GameFile::STATUS_TO_VERIFY || g.status == GameFile::STATUS_NEW
              =link_to t('admin.titles.pre_release') + ' ', pre_release_list_admin_game_path(g.game_id)
              i.icon-arrow-right
          td
            - if g.status == GameFile::STATUS_TO_VERIFY || g.status == GameFile::STATUS_VALIDATED
              =link_to t('admin.titles.submit_release') + ' ', submit_release_admin_game_path(g.game_id)
              i.icon-arrow-right
          td
            - case g.status
            -when GameFile::STATUS_TO_VERIFY
              =link_to t('admin.game.release_pass'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_VALIDATED)
              |
              =link_to t('admin.game.release_not_pass'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_REJECTED)
            -when GameFile::STATUS_VALIDATED
              =link_to t('admin.game.rollback'), audit_release_admin_game_path(:id => g.game_id, :game_file_id => g.id, :new_status => GameFile::STATUS_ROLLBACKED)
            - else
              'ddd'
          td
            =link_to t('admin.game.serial_number'), game_serial_numbers_admin_game_path(g.game_id)

app/views/admin/games/_unrelease.html.slim
- if @not_released_games.empty?
  = t 'admin.msg.no_game'
- else
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th = Game.human_attribute_name(:title)
        th =t 'admin.game.release_process'
        th = GameSerialNumber.model_name.human
    tbody
      - @not_released_games.each do |g|
        tr class=tr_with_status(g.status)
          td title=g.alias_name =g.title
          td
            =link_to t('admin.titles.pre_release') + ' ', pre_release_list_admin_game_path(g.id)
          td
            =link_to t('admin.game.serial_number'), game_serial_numbers_admin_game_path(g.id)
          td
            =link_to t('admin.game.serial_number'), admin_game_serial_numbers_path(g.id)

app/views/admin/games/delete_info.html.slim
<div class="widget">
  <div class="widget-content">
    <h3>序列号批量删除结果</h3>
    <div class="alert">
      <% if @used_count > 0 -%>
        <p>删除<%= @all_count - @used_count %>，已有<%= @used_count %>个序列号已被使用，请联系相关人员处理</p>
      <% else -%>
        <p>删除成功，共有<%= @all_count - @used_count %>个序列号被删除</p>
      <% end -%>
    </div>
    <%= link_to "返回", admin_game_serial_numbers_path(:game_id => @game.id), :class => "btn" %>
  </div>
</div>

app/views/admin/games/game_serial_numbers.html.slim
=render 'nav'
-content_for(:content) do
  h3=@game.title
  - unless @serial_number_types.empty?
    table.table.table-bordered.table-condensed
      thead
        th=GameSerialNumber.human_attribute_name(:serial_type)
        - index = (0..GameSerialNumber::STATUS_ALL-1) #include all tag
        - index.each do |i|
          th=GameSerialNumber.human_attribute_name(:status_arr)[i]
      tbody
        - @serial_number_types.each do |s|
          - next unless s
          tr
            td=s[:type_desc]
            - index.each do |i|
              td=s[:number][i] || 0
        tr
          td=GameSerialNumber.human_attribute_name(:status_arr)[GameSerialNumber::STATUS_ALL]
          td= @serial_number_total_count

  .btn-toolbar
    button.btn.btn-primary name="import_link" href="#import_div" data-toggle='modal' =t('admin.serial.import_serial_number')
    =link_to t('admin.serial.delete_serials'), delete_selection_admin_game_path(@game.id), :class => "btn btn-primary"
  =form_tag game_serial_numbers_admin_game_path, :method => :get, :class => 'form-search form-inline pull-right' do
    input name="game_id" value=@game.id type="hidden"/
    span
      input#search_text.input-medium.search-query name="query" type="text"/
    span
      input.btn.btn-primary type="submit" value=t('helpers.links.search') /
  ul#my_tab.nav.nav-tabs
    - @serial_number_counts.each do |s|
      li id=s.status
        =link_to(t('admin.serial.status')[s.status],game_serial_numbers_admin_game_path(@game, :status =>s.status))
  .tab-content
    - unless @admin_serial_numbers.empty?
      .tab-pane
        table.table.table-bordered.table-condensed.table-striped
          thead
            th=t('admin.titles.serial_type')
            th=t('admin.serial.serial_number')
            th=t('admin.serial.created_at')
            th=t('admin.serial.updated_at')
          tbody
            -@admin_serial_numbers.each do |serial_number|
              tr
                td= serial_number.serial_type.type_desc
                td= serial_number.serial_number
                td= sonkwo_time_format(serial_number.created_at)
                td= sonkwo_time_format(serial_number.updated_at)
        div=paginate @admin_serial_numbers, :class =>'pagination'
    -else
      =t('admin.msg.no-data')
  #import_div.modal.hide.fade role='dialog'
    .modal-header
      button.close data-dismiss='modal' aria-hidden='true'
        |
          &times;
      h3 =t('admin.titles.import_serial_numbers')
    =form_for(@game, :html => {:multipart => true, :id=>'import_form', :class=>'form-horizontal'},  :url => { :action => 'import_serials' }, :method => 'put') do |g|
      .modal-body
          .control-group
            label.control-label for='batch_number'
              =GameSerialNumber.human_attribute_name(:batch_number)
            .controls
              =select_tag('batch_number', options_for_select((0..34), 0))
          .control-group
            label.control-label for='serial_type'
              = GameSerialNumber.human_attribute_name(:serial_type)
            .controls
              =select_tag('serial_type', options_from_collection_for_select(@serial_types,'id', 'type_name'), prompt: t('helpers.tip.select_something'))
              =link_to(t('admin.serial.bind_new_type'), game_serial_type_admin_game_path)
              /<a id="bind_new_type_link" href="<%= admin_serial_types_path(:game_id => @game.id) -%>">绑定新类型</a>
          .control-group
            label.control-label for='serial_status'
              =GameSerialNumber.human_attribute_name(:status_arr)[GameSerialNumber::STATUS]
            .controls
              =select_tag('serial_status', options_from_collection_for_select(select_from_local_arrary(t('admin.serial.status')[0..2]),'value', 'content' ))
          .control-group
            .controls
              .alert.fade.in
                button.close data-dismiss='alert' type='button'
                strong
                  =t('helpers.tips.tip')
                  |:
                  =GameSerialNumber.human_attribute_name(:allocated_for_third_part)
          .control-group
            label.control-label for='serial_file'
              =GameSerialNumber.human_attribute_name(:serial_file)
            .controls
              =file_field_tag 'serial_file'
      .modal-footer
        input.btn.btn-primary type='submit'
          =t('helpers.links.submit')
-unless @admin_serial_numbers.empty?
  -content_for(:js_files) do
    javascript:
      $("##{@admin_serial_numbers.first.status}").addClass('active');