config/routes.rb
SonkwoCommunity::Application.routes.draw do
  begin
    devise_for :accounts, :controllers => { :sessions => 'account_sessions', :registrations => 'account_registrations' }
    devise_scope :accounts do
      get '/accounts/sign_out', to: 'account_sessions#destroy' # used for other platforms(store, forum)
    end
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end
  root :to => "home_pages#index"
  resources :home_pages, only: [:index]
  resources :groups do
    member do
      put 'add_user'
      delete 'remove_user'
      post 'add_tags'
      get 'posts'
      get 'members'
    end
    resources :posts, only: [:create]
  end

  resources :posts do
    resources :comments
    member do
      put 'like'
      delete 'unlike'
      post 'recommend'
    end
    resources :post_images, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    collection do
      put 'follow'
      delete 'unfollow'
      get 'check_name'
    end
    member do
      get 'groups'
      get 'posts'
      get 'people'
      get 'games'
      get 'games/:game_id', to: 'users#game'
      get 'games/:game_id/game_achievements', to: 'users#game_achievements'
    end
    resources :albums, only: [:index, :create, :show, :new] do
      resources :photos, only: [:index, :create]
    end
  end
  post 'photos/screenshot', to: 'photos#screenshot'

  resources :home, only: [:index] do
    collection do
      get 'index'
      get 'groups'
      get 'people'
      get 'posts'
      get 'notification'
      get 'recommended'
      put 'tags/:tag_id', to: 'home#add_tag'
      delete 'tags/:tag_id', to: 'home#remove_tag'
    end
  end

  resources :conversations, only: [:index, :show, :destroy]
  resources :private_messages, only: [:create, :destroy]
  resources :setting, only: [:index] do
    collection do
      get 'security'
      get 'password'
      put 'password', to: 'setting#update_password'
      post 'bind'
      get 'bind_complete'
    end
  end

  resources :cloud_storages, only: [:new, :create] do
    collection do
      get 'template'
    end
  end

  resources :games, only: [] do
    resources :game_achievements, only: [:index, :show]
    member do
      get :ranklist
    end
  end

  resources :informations, only: [:index] do
    collection do
      get :groups
      get :friends
      get :clients
      get :tags
      post :confirm_step
    end
  end

  resources :tipoffs, only: [:create]

  scope "(:locale)", locale: /zh|en/ do
    get '/admin', to: 'admin#index'
    namespace :admin do
      resources :games, only: [:index, :destroy] do
        member do
          get :pre_release_list
          get :submit_release
          get :new_pre_release
          get :audit_release
          get :game_serial_numbers
          get :delete_selection
          get :game_serial_type
          post :pre_release_list
          post :submit_release
          post :new_pre_release
          post :cancel_pre_release
          post :audit_release
          put :import_serials
          put :game_serial_type
        end
      end
      resources :auth_items
      resources :accounts, only: [:index, :edit]
      resources :serial_types
      resources :download_servers
      resources :clients
      resources :recommendations
      resources :all_games do
        resources :achievements
      end
    end
    resources :auth_items
    resources :accounts, only: [:index, :edit]
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # old routes (need to be cleaned in future)
  namespace :api do
    post 'client/post_err_msg', to: 'client#post_err_msg'
    get 'client/get_latest_client_version', to: 'client#get_latest_client_version'
    post 'user/post_action', to: 'user#post_action'
    post 'user/update_env', to: 'user#update_env'
    get 'user/get_play_time', to: 'user#get_play_time'
    get 'launch/get_launcher', to: 'launch#get_launcher'
    get 'game/list_my_games', to: 'game#list_my_games'
    get 'game/list_my_game_ids', to: 'game#list_my_game_ids'
    get 'game/get_game_info', to: 'game#get_game_info'
    get 'game/get_game_dlcs', to: 'game#get_game_dlcs'
    get 'game/request_game_shell', to: 'game#request_game_shell'
    get 'game/request_game_ini', to: 'game#request_game_ini'
    get 'game/get_game_seed', to: 'game#get_game_seed'
    get 'game/get_game_serial_number', to: 'game#get_game_serial_number'
    post 'game/register_serial_number', to: 'game#register_serial_number'
    get 'game/get_game_news', to: 'game#get_game_news'

  end
  # match ':controller(/:action(/:id))(.:format)'
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :games, only: [:index, :destroy] do
      member do
        get :pre_release_list
        get :submit_release
        get :new_pre_release
        get :audit_release
        get :game_serial_numbers
        get :delete_selection
        get :game_serial_type
        post :pre_release_list
        post :submit_release
        post :new_pre_release
        post :cancel_pre_release
        post :audit_release
        put :import_serials
        put :game_serial_type
      end
      resources:serial_numbers, only: [:index, :create], shallow: true do
        collection do
          get :delete_selection
          delete :delete_serials
          post :import
        end
      end
    end
    resources :auth_items
    resources :accounts
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # search api
  get 'search', to: 'search#index'
  get 'search/users', to: 'search#users'
  get 'search/posts', to: 'search#posts'
  get 'search/groups', to: 'search#groups'
end

app/controllers/home_controller.rb
require "sonkwo/behavior/fetcher"

class HomeController < ApplicationController
  before_filter :sonkwo_authenticate_account
  before_filter :check_update_tag, only: [:index]

  def index
    @new_talk = Post.new
    @new_talk.post_type = Post::TYPE_TALK
    qiniu_prepare(Settings.cloud_storage.post_bucket)

    params[:type] ||= "posts"
  end

  def groups
    @groups = current_account.groups.order("created_at DESC").page(params[:page]).per(10)
  end

  def people
    @type = params[:type] || "MUTUAL"
    @type = @type.strip.upcase

    select_items = %w(id nick_name exp follower_count following_count talk_count subject_count recommend_count is_mutual avatar)
    if @type == "FANS"
      @users = current_account.fans.select(select_items.join(",")).page(params[:page]).per(10)
      #current_account.notification.reset(:followed)
    elsif @type == "STARS"
      @users = current_account.stars.select(select_items.join(",")).page(params[:page]).per(10)
    else
      @users = Account.friends(current_account).select(select_items.join(",")).order("friendship.created_at DESC").page(params[:page]).per(10)
    end
  end

  def games
    #user_game_serials = UserGameSerial.by_account(current_account.id).includes(:game)
  end

  def posts
    params[:type] ||= "posts"
    if params[:type] == "posts"
      stream = Stream::Account.new(current_account, nil, min_id: params[:end_id].to_i, order: "created_at DESC")
      @stream_posts = stream.stream_posts.limit(9)
    elsif params[:type] == "groups"
      stream = Stream::Group.new(current_account, nil, min_id: params[:end_id].to_i, order: "created_at DESC")
      @stream_posts = stream.stream_posts.limit(9)
    else
      @stream_posts = []
    end

    respond_to do |format|
      format.html
      format.json
    end
  end

  def notification
    @notification = current_account.notification

    respond_to do |format|
      format.html
      format.json { render_for_api :notify, json: @notification, root: "data", meta: {status: "success"} }
    end
  end

  def recommended
    @recommends = Recommend.account_recommended(current_account.id).page(params[:page]).per(10)
    Post.downcast(@recommends, "original")
    current_account.notification.reset(:recommended)

    respond_to do |format|
      format.html
    end
  end

  def add_tag
    @tag = Tag.find(params[:tag_id])
    if current_account.tags.exists?(@tag) || current_account.tags << @tag
      render json: { status: "success", data: { id: @tag.id } }
    else
      render json: { status: "error", message: I18n.t("common.unknow_error") }
    end
  end

  def remove_tag
    @tag = Tag.find(params[:tag_id])
    if !current_account.tags.exists?(@tag) || current_account.tags.delete(@tag)
      render json: { status: "success", data: { id: @tag.id } }
    else
      render json: { status: "error", message: I18n.t("common.unknow_error") }
    end
  end

  private
  def check_update_tag
    redirect_to controller: :informations if current_account.update_tag.to_i < Account::UPDATE_TAG_FINISH
  end
end

app/views/home/_user.html.slim
.rs3.sns_release_fans.marAuto.user-item user_id=user.id
  .sns_release_fans_top
    .sns_release_fans_top_tx_kuang
      = link_to user_path(user) do
        = image_tag(user.avatar, height: 64, width: 64)
    .sns_release_fans_top_r
      .sns_release_fans_top_dj
        span.fans_top_dj_id
          = link_to user.nick_name, user_path(user)
      .sns_release_fans_top_cj
        span.fans_top_dj_dj
          | Lv #{user.level}
        span.fans_top_dj_dj_sj.total-level
          i.fans_top_dj_dj_sj_jdt.level level=user.level
      .sns_release_fans_top_bom
        span.fans_top_dj_id_sj
  .sns_release_fans_con
    ul
      li.sns_release_fans_con_fs
        = link_to user.follower_count, people_user_path(user, type: "fans")
      li.sns_release_fans_con_fx
        = link_to user.following_count, people_user_path(user, type: "stars")
      li.sns_release_fans_con_pl
        = link_to user.post_count, people_user_path(user, type: "stars")
      li.sns_release_fans_con_ft
        a href="#"
  .sns_release_fans_bom
    .fans_bom_l_yy
      span.fans_bom_sx
        a href="javascript:void(0);" =I18n.t("pages.send_pm")
      - if @type == "FANS"
        span.fans_bom_yc
          a href="javascript:void(0);" class="remove-fans" =I18n.t("pages.remove_fans")
      span.fans_bom_jb
        a href="javascript:void(0);" class="tip-off-user" =I18n.t("pages.tip-off")
    span.fans_bom_gz
      span
        - if user.is_mutual == Friendship::IS_MUTUAL
          a href="javascript:void(0);" class="btn btn-danger unfollow-user" =I18n.t("pages.unfollow_user")
          a href="javascript:void(0);" class="btn btn-danger follow-user" style="display: none;"  =I18n.t("pages.follow_user")
        - elsif @type == "STARS"
          a href="javascript:void(0);" class="btn btn-danger unfollow-user" =I18n.t("pages.unfollow_user")
          a href="javascript:void(0);" class="btn btn-danger follow-user" style="display: none;"  =I18n.t("pages.follow_user")
        - else
          a href="javascript:void(0);" class="btn btn-danger follow-user" =I18n.t("pages.follow_user")
          a href="javascript:void(0);" class="btn btn-danger unfollow-user" style="display: none;" =I18n.t("pages.unfollow_user")
      - if user.is_mutual == Friendship::IS_MUTUAL
        span.mutual
          | mutual

app/views/home/groups.html.slim
.sns_release
  .groups_inside
    - @groups.each do |group|
      .radius3px.sns_groups_data.marAuto
        .sns_groups_data_top
          .groups_top_tx
            = link_to group_path(group) do
              = image_tag(group.logo)
          .groups_top_new
            h1
              = link_to group.name, group_path(group)
              = link_to "", edit_group_path(group), class: "set fr" if group.creator_id == current_account.id
            span
              a href="/groups/#{group.id}" 已有#{group.member_count}位成员
            p =group.description
        .sns_groups_data_bottom
          .groups_b_jb
            a href="javascript:void(0);" 举报
          .groups_b_cz
            - if group.creator_id != current_account.id
              span.groups_b_cz_tc
                a href="/groups/#{group.id}/remove_user.json" 退出
            - else
              span.group-manage
                = link_to I18n.t("pages.manage"), edit_group_path(group)
            span.groups_b_cz_jr style="display: none;"
              a href="/groups/#{group.id}/add_user.json" 加入小组
  = paginate @groups

app/views/home/groups_posts.html.slim
- content_for(:jsfiles) do
  = javascript_include_tag "home/index"
  = javascript_include_tag "/javascripts/ckeditor/ckeditor.js"
.span2
  p= current_account.nick_name
  .span
    = image_tag(current_account.avatar.b.url, alt: current_account.nick_name, class: "img-rounded", width: "100px")
  p
    span
      = t("following")
      | :#{current_account.following_count}
    span
      = t("followers")
      | :#{current_account.follower_count}
    span
      = t("post")
      | :#{current_account.talk_count + current_account.subject_count}
.span9
  .row
    .btn-group
      a.btn.dropdown-toggle data-toggle="dropdown" href="#" 
        span.post-type-selected= t("talk")
        span.caret
      ul.dropdown-menu
        li
          a.post-type-item href="#" = t("talk")
        li
          a.post-type-item href="#" = t("subject")
    = form_for(@new_talk) do |f|
      p= f.text_area :content, class: "span9", rows: "3"
      p= f.submit t("send"), class: "btn btn-primary"
    = form_for @new_subject do |f|
      p= t("title")
      p= f.text_field :title, class: "span5"
      p= t("content")
      p= f.text_area :content, class: "span9", rows: "7"
      p= f.submit t("send"), class: "btn btn-primary"
  .row
    ul.nav.nav-tabs
      - if @type == "POSTS"
        li.active
          = link_to t("posts"), {controller: :home}
      - else
        li
          = link_to t("posts"), {controller: :home}
      - if @type == "GROUPS"
        li.active
          = link_to t("groups"), {action: :groups_posts, controller: :home}
      - else
        li
          = link_to t("groups"), {action: :groups_posts, controller: :home}
  ul.unstyled.container
    - @subjects.each do |subject|
      li
        = render partial: "subject", locals: {behavior: subject}

app/views/home/index.html.slim
-content_for :css_files do
  = stylesheet_link_tag "vendor/elastislide", media: "all"
  
-content_for :container_left do
  .SK-profile-card
    = link_to current_account.nick_name, user_path(current_account), class: "SK-account-name" 
    = link_to "更改设置", edit_account_registration_path(), class: "SK-account-edit"
    = link_to user_path(current_account), class: "SK-avatar" do
      = image_tag current_account.avatar, alt: current_account.nick_name, width: 60, height: 60
  ul.SK-nav.SK-nav-pills.SK-nav-stacked.SK-triangle-indicate
    li.active
      = link_to I18n.t("pages.my_home"), home_index_path
    li
      = link_to I18n.t("pages.my_private_messages"), conversations_path
    li
      = link_to I18n.t("pages.my_friends"), people_home_index_path
      
-content_for :container_right do
  .SK-content-communities
    .SK-content-community-list
      .SK-content-community-header
        h3 我的小组
        a#find-community-link 发现小组
      .SK-content-community-thumbs
        ul#carousel.elastislide-list
          li.all-groups
            a href="javascript:void(0);"
              img alt="所有信息" src="/all-groups.png" width="99px" height="99px"
          - current_account.groups.each do |group|
            li.hover-card data-type='group' data-id='#{group.id}'
              a href="#{group_path(group)}"
                img alt="#{group.name}" src="#{group.logo}" width="99px" height="99px"     
    .SK-content-community-detail
      .SK-community-title
        h3 小组的名称
      .SK-community-rank 
        h3 我在小组里的成就和排名
    .SK-container-right-left
      p 发布框
      p 信息排序方式选择
      p 信息流
      
    .SK-container-right-right
      p 小组信息
      p 小组成员
      p 关注的人关注该小组
      p 小组的杰出成员
      p 好友推荐

app/views/home/people.html.slim
.sns_release
  .groups_inside
  - @users.each do |user|
    = render partial: "user", locals: { user: user }
  = paginate @users

app/views/home/recommended.html.slim
ul.media-list
  -@recommends.each do |recommend|
    li.media
      = link_to user_path(recommend.creator), class: "pull-left" do
        = image_tag recommend.creator.avatar.m.url, alt: recommend.creator.nick_name, class: "media-object"
      div.media-body
        p.media-heading
          = link_to recommend.creator.nick_name, user_path(recommend.creator)
        div.media
          p= recommend.content
          -if recommend.original.cast.post_type == Post::TYPE_TALK
            p= recommend.original.content
          -else
            p= recommend.original.cast.title
            p= raw recommend.original.cast.content
= paginate @recommends