config/routes.rb
SonkwoCommunity::Application.routes.draw do
  begin
    devise_for :accounts, :controllers => { :sessions => 'account_sessions', :registrations => 'account_registrations' }
    devise_scope :accounts do
      get '/accounts/sign_out', to: 'account_sessions#destroy' # used for other platforms(store, forum)
    end
  rescue Exception => e
    puts "Devise error: #{e.class}: #{e}"
  end
  root :to => "home_pages#index"
  resources :home_pages, only: [:index]
  resources :groups do
    member do
      put 'add_user'
      delete 'remove_user'
      post 'add_tags'
      get 'posts'
      get 'members'
    end
    resources :posts, only: [:create]
  end

  resources :posts do
    resources :comments
    member do
      put 'like'
      delete 'unlike'
      post 'recommend'
    end
    resources :post_images, only: [:create, :destroy]
  end

  resources :users, only: [:show] do
    collection do
      put 'follow'
      delete 'unfollow'
      get 'check_name'
    end
    member do
      get 'groups'
      get 'posts'
      get 'people'
      get 'games'
      get 'games/:game_id', to: 'users#game'
      get 'games/:game_id/game_achievements', to: 'users#game_achievements'
    end
    resources :albums, only: [:index, :create, :show, :new] do
      resources :photos, only: [:index, :create]
    end
  end
  post 'photos/screenshot', to: 'photos#screenshot'

  resources :home, only: [:index] do
    collection do
      get 'index'
      get 'groups'
      get 'people'
      get 'posts'
      get 'notification'
      get 'recommended'
      put 'tags/:tag_id', to: 'home#add_tag'
      delete 'tags/:tag_id', to: 'home#remove_tag'
    end
  end

  resources :conversations, only: [:index, :show, :destroy]
  resources :private_messages, only: [:create, :destroy]
  resources :setting, only: [:index] do
    collection do
      get 'security'
      get 'password'
      put 'password', to: 'setting#update_password'
      post 'bind'
      get 'bind_complete'
    end
  end

  resources :cloud_storages, only: [:new, :create] do
    collection do
      get 'template'
    end
  end

  resources :games, only: [] do
    resources :game_achievements, only: [:index, :show]
    member do
      get :ranklist
    end
  end

  resources :informations, only: [:index] do
    collection do
      get :groups
      get :friends
      get :clients
      get :tags
      post :confirm_step
    end
  end

  resources :tipoffs, only: [:create]

  scope "(:locale)", locale: /zh|en/ do
    get '/admin', to: 'admin#index'
    namespace :admin do
      resources :games, only: [:index, :destroy] do
        member do
          get :pre_release_list
          get :submit_release
          get :new_pre_release
          get :audit_release
          get :game_serial_numbers
          get :delete_selection
          get :game_serial_type
          post :pre_release_list
          post :submit_release
          post :new_pre_release
          post :cancel_pre_release
          post :audit_release
          put :import_serials
          put :game_serial_type
        end
      end
      resources :auth_items
      resources :accounts, only: [:index, :edit]
      resources :serial_types
      resources :download_servers
      resources :clients
      resources :recommendations
      resources :all_games do
        resources :achievements
      end
    end
    resources :auth_items
    resources :accounts, only: [:index, :edit]
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # sidekiq
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  # old routes (need to be cleaned in future)
  namespace :api do
    post 'client/post_err_msg', to: 'client#post_err_msg'
    get 'client/get_latest_client_version', to: 'client#get_latest_client_version'
    post 'user/post_action', to: 'user#post_action'
    post 'user/update_env', to: 'user#update_env'
    get 'user/get_play_time', to: 'user#get_play_time'
    get 'launch/get_launcher', to: 'launch#get_launcher'
    get 'game/list_my_games', to: 'game#list_my_games'
    get 'game/list_my_game_ids', to: 'game#list_my_game_ids'
    get 'game/get_game_info', to: 'game#get_game_info'
    get 'game/get_game_dlcs', to: 'game#get_game_dlcs'
    get 'game/request_game_shell', to: 'game#request_game_shell'
    get 'game/request_game_ini', to: 'game#request_game_ini'
    get 'game/get_game_seed', to: 'game#get_game_seed'
    get 'game/get_game_serial_number', to: 'game#get_game_serial_number'
    post 'game/register_serial_number', to: 'game#register_serial_number'
    get 'game/get_game_news', to: 'game#get_game_news'

  end
  # match ':controller(/:action(/:id))(.:format)'
  get '/admin', to: 'admin#index'
  namespace :admin do
    resources :games, only: [:index, :destroy] do
      member do
        get :pre_release_list
        get :submit_release
        get :new_pre_release
        get :audit_release
        get :game_serial_numbers
        get :delete_selection
        get :game_serial_type
        post :pre_release_list
        post :submit_release
        post :new_pre_release
        post :cancel_pre_release
        post :audit_release
        put :import_serials
        put :game_serial_type
      end
      resources:serial_numbers, only: [:index, :create], shallow: true do
        collection do
          get :delete_selection
          delete :delete_serials
          post :import
        end
      end
    end
    resources :auth_items
    resources :accounts
    resources :serial_types
    resources :download_servers
    resources :clients
    resources :recommendations
    resources :all_games do
      resources :achievements
    end
  end

  # search api
  get 'search', to: 'search#index'
  get 'search/users', to: 'search#users'
  get 'search/posts', to: 'search#posts'
  get 'search/groups', to: 'search#groups'
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  layout false

  def index
    @recommendations = Recommendation.order("created_at DESC").limit(5)
  end
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/index.html.slim
doctype
html xmlns="http://www.w3.org/1999/xhtml"
  head
    meta content="text/html; charset=utf-8" http-equiv="Content-Type"
    title 杉果游戏导流页
    meta content="好玩的单机游戏,单机游戏大全,单机游戏下载,杉果游戏" name="keywords"
    meta content="杉果游戏，单机游戏下载大全,PC游戏,好玩的大型单机游戏,国内首家正版游戏数字商城" name="description"
    meta content="杉果游戏导流页" name="author"
    = stylesheet_link_tag "reset"
    = stylesheet_link_tag "home_pages/wwwstyle"
    = stylesheet_link_tag "storefooter"
  body
    .www_header
      .www_header_box
        .www_head_logo
          a.www_head_logo_bj href="#" target="_blank" title="杉果游戏"
        ul.www_nav_font
          li
            - if current_account
              = link_to current_account.nick_name, home_index_path
            - else
              = link_to I18n.t("pages.login"), new_account_session_path
          li
            - if current_account
              = link_to I18n.t("pages.quit"), destroy_account_session_path, method: :delete
            - else
              = link_to I18n.t("pages.register"), new_account_registration_path
          li
            a href="" target="_blank" 收藏
          li
            a href="#" target="_blank" 设为首页
    .www_carousel
      .www_carousel_box
        .www_carousel_box_L
          #banner
            .slides
              ul.slide-pic.radius3px
                li.cur
                  a href="#" target="_blank"
                    img alt="" src="images/banner_1.jpg"
              ul.slide-li.op
                li.cur
              ul.slide-li.slide-txt
                li.cur
                  a
          /! 轮播 代码 结束
        .www_carousel_box_R.radius3px
          .text_welcome
            h1 欢迎来到杉果游戏
            p 体验第九艺术的魅力，就在杉果游戏社区!
          .text_button
            = link_to I18n.t("pages.joinin_immidiately"), new_account_registration_path, class: "radius3px"
    .www_container
      .www_container_box
        ul
          li
            .box_store.radius3px
              h1 杉果游戏商城
              p 成百上千的正版单机大作，涵盖各种类型，让你尽情享受不同的游戏带给你的快感。
              span.fr
                a.store_col href="#" target="_blank" Go
          li
            .box_community.radius3px
              h1 杉果游戏社区
              p 秀成就，炫战绩，寻找基友战个痛；
              p 加小组，升等级，这里让你畅快聊！
              span.fr
                a.community_col href="#" target="_blank" Go
          li
            .box_forum.radius3px
              h1 杉果游戏论坛
              p 谈天说地聊人生，答疑解难侃大山。
              p 杉果论坛欢迎你。
              span.fr
                a.forum_col href="#" target="_blank" Go
          li
            .box_client.radius3px
              h1 杉果游戏客户端
              p 万千乐趣就从下载客户端开启……
              span.fr
                a.client_col href="#" target="_blank" Go
    .footer
      .footer_box
        .footer_box_mian
          span.fl
            a.footLogo href="#" target="_blank"
          span.fr
            ul.foot_navigation
              li
                a href="#" target="_blank" 关于中电博亚
                | |
              li
                a href="#" target="_blank" 关于杉果游戏
                | |
              li
                a href="#" target="_blank" 用户协议
                | |
              li
                a href="#" target="_blank" 客户服务
                | |
              li
                a href="#" target="_blank" 联系我们
        .footer_Copyright
          p &copy;2013 北京中电博亚科技有限公司版权所有 所有商标版权属于其拥有者 Tel:010-68434500
          p 京ICP备12041226号 《出版物经营许可证》 新出发京批字第直0816号 京公网安备11010802012421号
    = javascript_include_tag "jquery"
    = javascript_include_tag "jquery_ujs"